version: '3'
services:
  postgres:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=springboot
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
